Update issue templates
takeyu1013/qin-todo pull request #30
Opened 2022-02-26 08:51 UTC by takeyu1013

これはGitHubの標準のテンプレートを設定した際に自動生成されたものです。
Linked issuesのAssigneesが本ブランチをベースにpushするものとします。

2022-03-05 13:42 UTC, Natch requested changes
プロジェクトへの紐付け忘れてそうですー。

2022-03-05 13:46 UTC, Natch commented
97ab7dda65044783c5558ac1732b5a3e2096baaa
このコミットは main -> feature/#29_create_issues_template へのマージコミットを積むのではなく、
最新にした main に対して feature/#29_create_issues_template を rebase するとコミット履歴が荒れずにきれいになりそうです。

2022-03-05 13:46 UTC, Natch commented
### ask:
この ISSUE テンプレートは何を参考にされました？

2022-03-05 13:48 UTC, Natch commented on .github/ISSUE_TEMPLATE/bug_report_.md
> +1.
ステップで示すことが重要なら連番にしてあげたほうがよさそうです。
（毎回2番めを修正しなきゃいけなくなる）

2022-03-05 13:48 UTC, Natch commented on .github/ISSUE_TEMPLATE/bug_report_.md
> +-
箇条書きを例示しているのであれば、ハイフンが1個あれば十分かなと思いました。
（他も同様）

2022-03-05 14:18 UTC, takeyu1013 commented
> プロジェクトへの紐付け忘れてそうですー。

@Natch 
このPRに限ったことではない素朴な疑問なのですが、PRがIssueに紐づいている場合はPRがマージされると自動的に対応するIssueが閉じられて、対応するプロジェクトのIssue（元タスク）も完了になると思っていました。そのため、プロジェクトと紐づいているIssueと紐づいていればよいと思っていましたが、違いましたっけ？違っていたら申し訳ないです。

プロジェクトのタスクになく、いきなり作成されたPRは後から紐づけるしかない気はしています。後から一手間かける感じだとどうしても忘れることは仕方ないと思うので、できるだけ勝手に紐づいてくれるやり方でできるといいのですが。

2022-03-06 04:01 UTC, Natch commented
> > プロジェクトへの紐付け忘れてそうですー。
> 
> @Natch このPRに限ったことではない素朴な疑問なのですが、PRがIssueに紐づいている場合はPRがマージされると自動的に対応するIssueが閉じられて、対応するプロジェクトのIssue（元タスク）も完了になると思っていました。そのため、プロジェクトと紐づいているIssueと紐づいていればよいと思っていましたが、違いましたっけ？違っていたら申し訳ないです。
> 
> プロジェクトのタスクになく、いきなり作成されたPRは後から紐づけるしかない気はしています。後から一手間かける感じだとどうしても忘れることは仕方ないと思うので、できるだけ勝手に紐づいてくれるやり方でできるといいのですが。

なるほど。たしかにそうかもですね、後で確認しましょう！

2022-03-06 06:10 UTC, closed without merging